### ISSUE TITLE
PXE server for base ubuntu install

### ISSUE THREAD

**Issue by eby** [aadl/catalog-stations#20]
Need to work on basic pxe install of base ubuntu image so it is easy to reinstall in the field. 

Basic UEFI compatible method: https://wiki.ubuntu.com/UEFI/PXE-netboot-install

That refers to kickstart though preseed can do a more unattended install.

**Comment by taleon** [comment]
grub.cfg needs to be modified to have these boot parameters to workaround some bugs with preseed installations:
```
menuentry "Install Ubuntu Server" {
	set gfxpayload=keep
	linux	/install/vmlinuz  file=/cdrom/preseed/ubuntu-server.seed auto url=http://path.to/preseed.cfg debian-installer/locale=en_US keyboard-configuration/layoutcode=us netcfg/hostname=catalog-station priority=critical quiet ---
	initrd	/install/initrd.gz
}
```
These boot parameters don't take effect if only set in preseed file. priority=critical prevents installer from asking to verify hostname, even though it is correctly set. auto sets the unattended install to go through prompts where values have already been defined.
